### PR TITLE
MInor bug fixed: Terms and condition page updated, not redirecting to home

### PR DESCRIPTION
**Pull request by Jay-1409**
Fixed the bug.
#397

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
image


this not good...double check once before raising PR

**Comment by manikumarreddyu** [comment]
image

for minor bug ..lol

**Comment by Jay-1409** [comment]
https://github.com/user-attachments/assets/ecd7493e-adee-4ef4-bf6d-f5b8773a6885

**Comment by Jay-1409** [comment]
> image
> this not good...double check once before raising PR

Yeah actually i npm installed in the wrong frontend.. my bad hehe

**Comment by Jay-1409** [comment]
should i reclone and redo it ?

**Comment by manikumarreddyu** [comment]
https://www.linkedin.com/in/manikumarreddyu

connect me here i tell you the shortcut

**Comment by Jay-1409** [comment]
> https://www.linkedin.com/in/manikumarreddyu
> 
> connect me here i tell you the shortcut

but we are already connected on linkedin!!

**Comment by manikumarreddyu** [comment]
Msg me once

**Comment by Jay-1409** [comment]
> Msg me once

yea bro done

**Pull request closed without merging**
