### PR TITLE
Improve the Prices Section

### PR DESCRIPTION
**Pull request by 13Sharad**
# Pull Request

### Description
This pull request updates the Prices component by improving dynamic background color generation based on percentage change, adding sorting functionality, and enhancing hover animations. Error handling has also been introduced for better user feedback during data fetching.

### Related Issues
#130 

### Changes Made
1.Added error handling for data fetching failures.
2.Dynamic hover animations for better UX.
3.Sorting functionality for top gainers/losers.
4.Fixed duplicate viewCount state.

### Checklist 

- [yes ] I have tested the changes locally
- [ no] Documentation has been updated (if necessary)
- [no ] Changes are backward-compatible

### Screenshots (if applicable)
N/A

### Additional Notes
N/A

Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hi @13Sharad what you have mentioned in the issue is not matching with this PR...
give me explanation..why you did this

**Comment by 13Sharad** [comment]
Screenshot :-

IMG_20241008_140103

1. I Adding Sort Ascending and Sort Descending button, this allow users to view the top gainers and losers in ascending or descending order based on the percentage change. I did this by :-

1.Introducing a new state sortOrder that tracks whether the sort is 'asc' or 'desc'.
3.Adding a sortData function that sorts the data array based on the selected order.
4.Creating two buttons, "Sort Ascending" and "Sort Descending", that toggle the sort order when clicked, providing users with the ability to customize the data display interactively.

2. I added Error Handling: If data fetching fails, an error message is displayed to the user.

3. I added Dynamic Hover Animations: Hover effects like scaling and shadow changes are added for a better user experience. If u click top gainers and top losses card section then u see effect.

4.I added Duplicate State Fix: You fixed the duplicate viewCount state declaration for a cleaner state management.

Check my pull request code then u understand what I change that in a code.

**Comment by manikumarreddyu** [comment]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A real-time crop price monitoring feature that provides farmers with updates on market prices for various crops, enabling them to make informed decisions about the best time to sell their produce.

### Use Case

Farmers can monitor price fluctuations and decide when to sell their crops at the most profitable time, optimizing their earnings.

### Benefits

1.Helps farmers maximize profits
2.Improves decision-making
3.Supports sustainable farming

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
is that what you said in issue description ?

**Pull request merged**
