### PR TITLE
Explore more page which is a compilled library of all the functions in the website created.

### PR DESCRIPTION
**Pull request by Jay-1409**
Explore more page which is a compilled library of all the functions in the website created.
# Pull Request

### Title
Explore more page which is a compilled library of all the functions in the website created.

### Related Issues
#289 

### Changes Made
- new page added

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
image
image

### Additional Notes
Thanks for letting me contribute in this awesome project.

Footer

### CODE REVIEW

**Comment by Jay-1409** [comment]
plaese check it @manikumarreddyu

**Comment by manikumarreddyu** [comment]
ok..i will merge it no..issues..

**Comment by Jay-1409** [comment]
> ok..i will merge it no..issues..

okay but please merge it before any conflicts comes :)

**Comment by manikumarreddyu** [comment]
bro it is failing...see for errors

**Comment by Jay-1409** [comment]
> bro it is failing...see for errors

bro check this link if it works https://agro-tech-hcx9r84zd-manikumarreddyus-projects.vercel.app/products

**Comment by Jay-1409** [comment]
> > bro it is failing...see for errors
> 
> bro check this link if it works https://agro-tech-hcx9r84zd-manikumarreddyus-projects.vercel.app/products

it had deployed successfully earlier I think

**Comment by Jay-1409** [comment]
It is now working @manikumarreddyu

**Pull request merged**
