### PR TITLE
Fix Navbar distortion caused by the addition of "Irrigation system" item

### PR DESCRIPTION
**Pull request by rebornstar1**
# Pull Request

### Title
Fix Navbar distortion caused by the addition of "Irrigation system" item

### Description
This PR addresses the issue where the navbar layout became distorted after adding a new item labeled "Irrigation system." The issue was due to insufficient space and CSS conflicts that caused the navbar to overflow and misalign. Adjustments have been made to ensure the navbar maintains its proper alignment and responsiveness, accommodating the new item without breaking the layout.

### Related Issues
#171

### Changes Made
Adjusted the CSS for the navbar to accommodate the new "Irrigation system" item.

### Checklist 

- [X] I have tested the changes locally
- [X] Documentation has been updated (if necessary)
- [X] Changes are backward-compatible

### Screenshots (if applicable)
Not Necessary

### Additional Notes

Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
image



no change

**Comment by rebornstar1** [comment]
image

See the Preview Deployment Please

**Comment by manikumarreddyu** [comment]
image


i am using 14 inch laptop..i think you are using 15 inch..

**Comment by rebornstar1** [comment]
Yes

**Pull request merged**
