### PR TITLE
Created a yield prediction mode

### PR DESCRIPTION
**Pull request by AYUSHI-SHA**
# Pull Request

### Title
Created a yield prediction mode

### Description
The primary goal of this model is to estimate crop yield based on various factors such as Area, Item, Year, Average Rainfall, Pesticides, and Average Temperature. The project utilizes a Random Forest Regressor to predict the yield based on historical dataset downloaded from kaggle.

### Changes Made
1. **Data Preprocessing**: Loaded the dataset and removed unnecessary columns for clarity. Encoded categorical features (Area and Item) using LabelEncoder to convert them into numerical format suitable for model training.

2. **Model Training**: Split the dataset into training and testing sets to evaluate model performance effectively. Trained a Random Forest Regressor on the training data to learn patterns associated with crop yield.

3. **Input Encoding**: Developed a function to encode user input for Area and Item dynamically, ensuring that inputs are properly normalized and encoded before making predictions. Handled unknown values gracefully by providing informative error messages when user inputs are not present in the training data.

4. **Yield Prediction Functionality**: Created a user-friendly interface for users to input the required features for yield prediction. Integrated the trained model to generate and display predictions based on user inputs.

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @AYUSHI-SHA you have to follow the template which is provided for making a PR ..other wise you will not get points...because when ever a PR is merged ..if you mention issues number which is fixed ..then that issue automatically closes and you will get points...

check it once ..

**Comment by manikumarreddyu** [comment]
image


you have to follow the structure dont simply copy paste from chatgpt...

modify the content according to template provided ...
kindly requesting you... @AYUSHI-SHA ..i hope you got my point....

**Comment by AYUSHI-SHA** [comment]
I am really sorry sir,
This was the first time I have been contributing to open source and overlooked this important point. I will make the necessary changes and follow the structure for the PR. 
I regret the inconvenience caused to you.

**Comment by manikumarreddyu** [comment]
learning is the key...keep learning from mistakes...dont ever repeat the same mistakes again..
@AYUSHI-SHA good work..

**Comment by manikumarreddyu** [comment]
Hi @AYUSHI-SHA excellent work...you are a fast learner yaar..it's enough..keep rocking with some more issues and solutions...
Thank you.
All the best @AYUSHI-SHA

**Comment by manikumarreddyu** [comment]
There is a small mistake...fixed #85 it is wrong.. there youbhave to give issue number not PR number...change it...that all.. everything looks fine

**Comment by manikumarreddyu** [comment]
Issue no is 64...check it once

**Comment by AYUSHI-SHA** [comment]
Made the required changes.
Thankyou so much for your guidance, Sir!

**Comment by manikumarreddyu** [comment]
hi @AYUSHI-SHA  if you can create frontend and api.. i will put labels here..because without froontend there is no use of it..and causing problems in cloning for others..please let me know if you can create frontend part...as of now you are simply getting projects from somewhere in other repos and pasting them here...im sorry for removing labels..if you do fronend and api part i can relabel them ..i think you understand my point...simply having notebook files does nothing..until now..which are in notebooks..all of them have frontend and api..
thank you @AYUSHI-SHA

**Pull request merged**
