### PR TITLE
Integrate Password Recovery Feature

### LINKED ISSUE #592: [Feature Request]: Integrate Password Recovery Feature
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Integrate the Password Recovery Feature to enable users to reset their passwords seamlessly. This enhancement involves connecting the frontend with APIs (or backend in the future) to send OTPs, verify them, and allow password reset.

### Use Case

This feature will allow users to quickly regain access to their accounts in case they forget their passwords. For example, if a user cannot log in, they can enter their email to receive an OTP, verify it, and set a new password.

### Benefits

Improves user experience by providing a recovery mechanism.
Reduces user frustration and prevents account lockouts.
Prepares the frontend for smooth integration with future backend OTP and email services.

### Add ScreenShots

Screenshot 2024-10-20 025545
Screenshot 2024-10-15 192639
Screenshot 2024-10-20 014214

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by saras-69**
# Pull Request

### Title
Integrate Password Recovery Feature

### Description
This PR adds the Password Recovery feature, allowing users to reset their forgotten passwords with ease. It includes the front-end flow without backend integration, simulating OTP verification via alerts. The feature improves the user experience by providing a seamless way to regain access to accounts.

### Related Issues

Fixes #592 

### Changes Made

Created Password Recovery component in React.
Added OTP input fields and reset password form.
Implemented alert-based OTP simulation for demonstration.
Included CSS for responsive design.

### Checklist 

- [ x] I have tested the changes locally
- [ x] Documentation has been updated (if necessary)
- [ x] Changes are backward-compatible

### Screenshots (if applicable)

Screenshot 2024-10-21 232232

https://github.com/user-attachments/assets/4ed86ae6-8ffa-45db-a011-d1f7acf397d8

### Additional Notes

This feature currently uses alert-based OTP simulation. It can be expanded in the future with API calls for OTP generation and verification once backend support is available.

Footer

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
@saras-69 I actually wanted to implement this and I was curious to know how it was implemented. May I please know how this is sending OTP to email and how the forget password mechanism works? I don't quite see a section of code for that implementation part. Please implement it properly. Or let others work. No harm intended! Thanks. 

In addition, could u please tell why the single quotes are changed to double quotes everywhere? This action would seriously affect other's PRs and would result us everyone into merge conflicts. So, I suggest you to revert them back. 

image

**Comment by saras-69** [comment]
> @saras-69 I actually wanted to implement this and I was curious to know how it was implemented. May I please know how this is sending OTP to email and how the forget password mechanism works? I don't quite see a section of code for that implementation part. Please implement it properly. Or let others work. No harm intended! Thanks.
> 
> In addition, could u please tell why the single quotes are changed to double quotes everywhere? This action would seriously affect other's PRs and would result us everyone into merge conflicts. So, I suggest you to revert them back.
> 
> image

It makes sense that an extension could automatically enforce different formatting rules, such as changing single quotes to double quotes. Extensions like Prettier or ESLint can be configured to apply specific code style guidelines when you save or format files.

**Comment by saras-69** [comment]
@J-B-Mugundh Ok, I will work on sending the OTP. I forgot to do this since I was used to sending a recovery link to the email for resetting the password in a previous project due to security concerns. That's why using OTP didn’t come to mind initially.

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh Ok, I will work on sending the OTP. I forgot to do this since I was used to sending a recovery link to the email for resetting the password in a previous project due to security concerns. That's why using OTP didn’t come to mind initially.

Okay great! Carry on. U can ping here in case u r stuck or need help.

**Comment by saras-69** [comment]
> > @J-B-Mugundh Ok, I will work on sending the OTP. I forgot to do this since I was used to sending a recovery link to the email for resetting the password in a previous project due to security concerns. That's why using OTP didn’t come to mind initially.
> 
> Okay great! Carry on. U can ping here in case u r stuck or need help.

Sure

**Comment by manikumarreddyu** [comment]
> > @saras-69 I actually wanted to implement this and I was curious to know how it was implemented. May I please know how this is sending OTP to email and how the forget password mechanism works? I don't quite see a section of code for that implementation part. Please implement it properly. Or let others work. No harm intended! Thanks.
> > In addition, could u please tell why the single quotes are changed to double quotes everywhere? This action would seriously affect other's PRs and would result us everyone into merge conflicts. So, I suggest you to revert them back.
> > image
> 
> It makes sense that an extension could automatically enforce different formatting rules, such as changing single quotes to double quotes. Extensions like Prettier or ESLint can be configured to apply specific code style guidelines when you save or format files.

You just used ..chatgpt or any other ai tools...that's it I guess ....the total file changed....you just created a frontend recovery page that's it . nothing morethan that...and sorry to inform you that I am closing this PR ..issue as well... because this is the heart of the project I don't want to ruin it ..

**Comment by saras-69** [comment]
> > > @saras-69 I actually wanted to implement this and I was curious to know how it was implemented. May I please know how this is sending OTP to email and how the forget password mechanism works? I don't quite see a section of code for that implementation part. Please implement it properly. Or let others work. No harm intended! Thanks.
> > > In addition, could u please tell why the single quotes are changed to double quotes everywhere? This action would seriously affect other's PRs and would result us everyone into merge conflicts. So, I suggest you to revert them back.
> > > image
> > 
> > 
> > It makes sense that an extension could automatically enforce different formatting rules, such as changing single quotes to double quotes. Extensions like Prettier or ESLint can be configured to apply specific code style guidelines when you save or format files.
> 
> You just used ..chatgpt or any other ai tools...that's it I guess ....the total file changed....you just created a frontend recovery page that's it . nothing morethan that...and sorry to inform you that I am closing this PR ..issue as well... because this is the heart of the project I don't want to ruin it ..

When you save the file the extension will automatically change the format

**Comment by saras-69** [comment]
> > > @saras-69 I actually wanted to implement this and I was curious to know how it was implemented. May I please know how this is sending OTP to email and how the forget password mechanism works? I don't quite see a section of code for that implementation part. Please implement it properly. Or let others work. No harm intended! Thanks.
> > > In addition, could u please tell why the single quotes are changed to double quotes everywhere? This action would seriously affect other's PRs and would result us everyone into merge conflicts. So, I suggest you to revert them back.
> > > image
> > 
> > 
> > It makes sense that an extension could automatically enforce different formatting rules, such as changing single quotes to double quotes. Extensions like Prettier or ESLint can be configured to apply specific code style guidelines when you save or format files.
> 
> You just used ..chatgpt or any other ai tools...that's it I guess ....the total file changed....you just created a frontend recovery page that's it . nothing morethan that...and sorry to inform you that I am closing this PR ..issue as well... because this is the heart of the project I don't want to ruin it ..

@manikumarreddyu Here you can see  ---|
                                                                    |
                                                                    |
https://github.com/user-attachments/assets/cb6013ab-1833-4d7f-ab39-a325fdbe86ff

**Comment by manikumarreddyu** [comment]
ok...then.. what is the use of this feature which you have done...just sending recovery mail..thats it..

**Comment by saras-69** [comment]
> ok...then.. what is the use of this feature which you have done...just sending recovery mail..thats it..

Yes but I will improve it

**Comment by saras-69** [comment]
> ok...then.. what is the use of this feature which you have done...just sending recovery mail..thats it..

Could you please let me know if I can proceed with this contribution, or if there are any specific guidelines you'd like me to follow?

**Pull request closed without merging**
