### PR TITLE
Enhanced styling of FAQ

### LINKED ISSUE #231: [Feature Request]: Add hover effect on FAQ
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It would look more appealing if there could have been an effect upon hiver on FAQ question

### Use Case

It will look more good

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by jvkousthub**
# Pull Request

### Title
Add hover effect to FAQ

### Description
This pull request replaces the click functionality with hover functionality for displaying FAQ answers. When a user hovers over a question, the corresponding answer will be displayed.

### Related Issues
Fixes #231 

### Changes Made
Updated styles to ensure consistent appearance when hovered.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

https://github.com/user-attachments/assets/37582b4e-e8d1-49c0-8fe4-1f8c5a624a77

### Additional Notes

Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
can you please make it like in style share app

**Comment by manikumarreddyu** [comment]
image


https://style-share.vercel.app/app/

add some more question and answers also

**Comment by jvkousthub** [comment]
@manikumarreddyu provide me with the questions to add

**Comment by manikumarreddyu** [comment]
> @manikumarreddyu provide me with the questions to add

try it with chatgpt...

and also it converts easily from tsx to jsx..

**Comment by jvkousthub** [comment]
done @manikumarreddyu

**Pull request merged**
