### PR TITLE
Enhanced Navbar Content Visibility and Added Icons

### PR DESCRIPTION
**Pull request by Sanikaaher-19**
feat  #77

Title:
 Enhanced Navbar Content Visibility and Added Icons

Description:
This pull request enhances the visibility of the navbar content by adding icons to each navigation link. The added icons improve the overall user experience by providing a clear visual representation of each link's purpose.

Icons Added:

Home icon for the home link
Crop icon for the crop link
Disease icon for the disease link
Fertilizer icon for the fertilizer link
Soil Quality icon for the soil quality link
Price icon for the price link
Forecast icon for the forecast link

### CODE REVIEW

**Comment by Sanikaaher-19** [comment]
@manikumarreddyu 
added a pull request but @vercel showing something error

**Comment by manikumarreddyu** [comment]
check for any errors in ypur code..try to run this command in fronend folder>> npm run build..it will show you any potential errors @Sanikaaher-19

**Comment by manikumarreddyu** [comment]
i think ..it is better to close this PR and also one thing which is important is..you are using css and js files..please dont do that ...only use tailwind css for styling navbar and also use react icons for placing icons in navbar...

1. i think you have uploaded node modules also..dont do that
2.delete this current branch 
3. create a new branch 
4.style the navbar only with tailwind css and react-icons...
5.the next time when you raise a PR there should changes only in Navbar.tsx file...other than that dont make changes in other files..

if you have any doubts please contact me linkedin ...see mygithub file..there you will get linkedin profile..
thank you @Sanikaaher-19

**Comment by manikumarreddyu** [comment]
better to close this..and raise a new PR 
add .nodemodules to gitignore...

**Comment by manikumarreddyu** [comment]
hey @Sanikaaher-19 any updates ..?

**Comment by Sanikaaher-19** [comment]
I am working on it......

**Comment by manikumarreddyu** [comment]
if you face any problems..lets have google meet..if you are okay.. @Sanikaaher-19

**Comment by Sanikaaher-19** [comment]
i am trying to solve issue it will be solve .....

**Comment by manikumarreddyu** [comment]
hi @Sanikaaher-19 any updates  ??

**Comment by manikumarreddyu** [comment]
image


i solved the erros..it is not looking beautiful..

add the below code
import { useState } from 'react';
import { Link } from 'react-router-dom';
// import { FaSun, FaMoon } from 'react-icons/fa'; // Import icons from react-icons
import { FaSeedling, FaBacteria,FaMoneyBillWave ,FaCloudSun } from 'react-icons/fa';
import icon from '../assets/favicon2.png';
import {FaHome} from 'react-icons/fa';

// import useTheme from '../hooks/useTheme'; // Import useTheme hook

const Navbar = () => {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    // const { theme, toggleTheme } = useTheme(); // Use useTheme hook

    const toggleMenu = () => {
        setIsMenuOpen(!isMenuOpen);
    };
    
    const closeMenu = () => {
        setIsMenuOpen(false);
    };
    
    return (
        <nav className={`bg-gradient-to-r from-[#11cb46] via-[#3ff132] to-[#04ba10] fixed w-full  z-20 top-0 start-0  `}>
            <div className="max-w-screen-xl flex flex-wrap items-center font-semibold justify-between mx-auto p-3">
                <div className="text-white font-bold flex items-center">
                    icon
                    <span className="px-2 text-xl">AgroTech AI</span>
                </div>
                <button
                    onClick={toggleMenu}
                    type="button"
                    className="relative inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-100 rounded-lg lg:hidden hover:bg-green-400 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    aria-controls="navbar-default"
                    aria-expanded={isMenuOpen ? "true" : "false"}
                >
                    <span className="sr-only">Open Menu</span>
                    <div className="flex flex-col gap-1">
                        <span className={`h-0.5 w-4 bg-white transform transition duration-200 ease-in ${isMenuOpen ? "rotate-[45deg]" : "rotate-0"}`}></span>
                        <span className={`h-0.5 w-4 ${isMenuOpen ? "bg-transparent" : "bg-white"} transition duration-200 ease-in ${isMenuOpen ? "absolute" : "relative"}`}></span>
                        <span className={`h-0.5 w-4 bg-white transform transition duration-200 ease-in ${isMenuOpen ? "rotate-[-45deg]" : "rotate-0"} ${isMenuOpen ? "absolute" : "relative"}`}></span>
                    </div>
                </button>
                <div className={`${isMenuOpen ? "block" : "hidden"} w-full lg:block lg:w-auto transition-all duration-300 ease-in-out`} id="navbar-default">
                    <div className="flex flex-col lg:flex-row lg:items-center lg:space-x-4">
                        <Link to="/" className="block py-2 px-5 text-white hover:text-black-200 text-center" onClick={closeMenu}>
                           <FaHome className="navbar-icon mr-2" /> Home
                        </Link>
                        <Link to="/crop" className="block py-2 px-5 text-white hover:text-black-200 text-center" onClick={closeMenu}>
                           <FaSeedling className=" navbar-icon mr-2" /> Crop
                        </Link>
                        <Link to="/disease" className="block py-2 px-5 text-white hover:text-black-200 text-center" onClick={closeMenu}>
                            <FaBacteria className="navbar-icon mr-2" />Disease
                        </Link>
                        <Link to="/fertilizer" className="block py-2 px-5 text-white hover:text-black-200 text-center" onClick={closeMenu}>
                           Fertilizer
                        </Link>
                        <Link to="/soil" className="block py-2 px-5 text-white hover:text-black-200 text-center" onClick={closeMenu}>
                         Soil Quality
                        </Link>
                        <Link to="/prices" className="block py-2 px-5 text-white hover:text-black-200 text-center" onClick={closeMenu}>
                           <FaMoneyBillWave className="navbar-icon mr-2"/>Price
                        </Link>
                        <Link to="/forecast" className="block py-2 px-5 text-white hover:text-black-200 text-center" onClick={closeMenu}>
                        <FaCloudSun className="navbar-icon mr-2" /> Forecast
                        </Link>
                    </div>
                </div>
                {/* <button
                    className="inline-flex   items-center justify-center w-10 h-10 text-gray-100 rounded-lg hover:bg-green-400 focus:outline-none focus:ring-1 focus:ring-gray-200"
                    onClick={toggleTheme}
                >
                    {theme === 'light' ? <FaMoon className="text-2xl p-1" /> : <FaSun className="text-2xl p-1" />}
                </button> */}
            </div>
        </nav>
    );
} 
export default Navbar;

**Pull request merged**
