### PR TITLE
Fixed the issues in the contact page the commented parts i fixed.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Pull Request

### Title
Fixed the issues in the contact page the commented parts i fixed.

### Description
Fixed the issues in the contact page the commented parts i fixed.

### Related Issues
#143 related to this issue we talked in this  the pull request #164 

### Changes Made
Changed the commented part again with the original code.

### Checklist 
- [X] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [X] Changes are backward-compatible

### Screenshots (if applicable)
image

@manikumarreddyu Check this PR and merge it i have fixed the issue. Assign this to me and put relevent labels like gssoc 2024 ext and hacktoberfest and level.

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
image


can you put here related icons..

**Comment by tarunkumar2005** [comment]
@manikumarreddyu Ya will do that this was my original issue.

**Comment by manikumarreddyu** [comment]
no problem i will fix it...i am merging this...no worries @tarunkumar2005

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review it

**Pull request merged**
