### PR TITLE
Added the visitor count

### LINKED ISSUE #674: [Feature Request]: Add a Visitor Counter feature ✨
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Visitor Counter feature properly.

@manikumarreddyu Please assign me the work

### Use Case

The feature would show the visitor count 

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-10-26 004029
Screenshot 2024-10-26 004024

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Peart-Guy**
# Pull Request

### Title
I added a visitor count 

### Description
My work shows number of visitor 

### Related Issues
Fixes #674

### Changes Made
I added the visitor counter 

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
Screenshot 2024-10-27 180548

### Additional Notes

Footer

@manikumarreddyu  Please give higher level as other PA are giving

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
can you please share me the working video of it..i cant able to see it in deployment..

**Comment by Peart-Guy** [comment]
> can you please share me the working video of it..i cant able to see it in deployment..

You can see it if you run the index.html

**Comment by manikumarreddyu** [comment]
image


it is hiding..and it is not appearing fully...

**Comment by manikumarreddyu** [comment]
Screenshot_2024-10-30-15-56-50-471_com android chrome


Screenshot_2024-10-30-15-56-45-889_com android chrome


What is this man... please rectify it

**Comment by Peart-Guy** [comment]
> image
> it is hiding..and it is not appearing fully...



@manikumarreddyu  I have updated kindly check it out

**Comment by Peart-Guy** [comment]
@manikumarreddyu  
I have updated it. Knidly check it out

image

**Pull request merged**
