### PR TITLE
Animation added to elements : Issue no #233

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
# Pull Request

### Title
Animation added to elements of Home page

### Description

- Implemented animations for various elements on the Home page using framer-motion.
- Added distinct fade-in animations for the heading, paragraph, and button in the hero section.
- Animated the "How It Works" section with staggered animations for each step.
- Incorporated animations for the Features, About, Showcase, Testimonial, and FAQ sections, with specific delays for a smoother scrolling experience.

### Related Issues
Fixes : #233 

### Changes Made
New feature

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

https://github.com/user-attachments/assets/b0fd31bd-60f9-4583-acb8-669de608f925

https://github.com/user-attachments/assets/a00ee920-1eae-470b-923b-eec777912ade

### CODE REVIEW

**Comment by AbhijitMotekar99** [comment]
Hey @manikumarreddyu 
I close #320 
And Raise new PR by removing Node modules

**Comment by manikumarreddyu** [comment]
Run this command in your local..

npm run build

It will show you potential errors

**Comment by AbhijitMotekar99** [comment]
Hey @manikumarreddyu 
### Build Error Solved
Agro nom run build

**Comment by manikumarreddyu** [comment]
image


please remove the node modules   @AbhijitMotekar99

**Comment by AbhijitMotekar99** [comment]
Node modules removed

**Comment by manikumarreddyu** [comment]
hi @AbhijitMotekar99 im sorry for the inconvenience... you can do this after entire desin of home page is over.. i will update you later..
thank you @AbhijitMotekar99

**Comment by manikumarreddyu** [comment]
image


dont send node modules in pr s
remove that files which are outside of frontend folder

**Comment by AbhijitMotekar99** [comment]
So now I have to make changes or wait till UI finished

**Comment by manikumarreddyu** [comment]
see the above comment once...

**Comment by manikumarreddyu** [comment]
raise a new pr bro..

**Comment by manikumarreddyu** [comment]
https://www.linkedin.com/in/manikumarreddyu/

connect me here once..we will discuss

**Comment by manikumarreddyu** [comment]
Screenshot_2024-10-13-09-41-05-515_com android chrome


It became outdated...

**Comment by AbhijitMotekar99** [comment]
So can I raise new PR

**Comment by manikumarreddyu** [comment]
Yes..there should be only changed files nothing else...be careful...don't do any mistakes this time..
Thank you @AbhijitMotekar99

**Pull request closed without merging**
