### PR TITLE
Animation added to elements : Issue no #233

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
# Pull Request

### Title
Animation added to elements of Home page

### Description

- Implemented animations for various elements on the Home page using framer-motion.
- Added distinct fade-in animations for the heading, paragraph, and button in the hero section.
- Animated the "How It Works" section with staggered animations for each step.
- Incorporated animations for the Features, About, Showcase, Testimonial, and FAQ sections, with specific delays for a smoother scrolling experience.

### Related Issues
Fixes : #233 

### Changes Made
New feature

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

https://github.com/user-attachments/assets/b0fd31bd-60f9-4583-acb8-669de608f925

https://github.com/user-attachments/assets/a00ee920-1eae-470b-923b-eec777912ade

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
remove node modules bro

**Comment by AbhijitMotekar99** [comment]
Hey @manikumarreddyu 
I added a smooth transition to the elements, so you can check how they appear when they are visible—there's no lag in the animation. I also made slight changes to the hero image. I had already done this a few days ago on the old UI, but today, because of the changes in UI, I had to do it again. Thanks for waiting!

**Comment by manikumarreddyu** [comment]
image

please remove node modules

**Comment by AbhijitMotekar99** [comment]
> image
> please remove node modules

OK

**Pull request closed without merging**
