### PR TITLE
Add Frontend for Sugarcane Disease Prediction Backend

### PR DESCRIPTION
**Pull request by IkkiOcean**
# Pull Request

### Title
Frontend for Sugarcane Disease Prediction Backend

### Description
This PR introduces significant changes to the frontend for the crop disease prediction feature, specifically for sugarcane. It also enhances the crop selection process and introduces dedicated engine pages for each crop. Image uploads are dynamically routed to the corresponding backend based on the selected crop.

### Related Issues
closes: #157 

### Changes Made
- **Revamped Crop Selection Page**: 
  - Redesigned the layout and UI to make the crop selection process more intuitive and visually appealing.
- **Dedicated Engine Pages for Each Crop**:
  - Each crop now has its own page with relevant disease necessities and prevention tips.
- **Dynamic Image Upload**: 
  - Image uploads are now routed to different backends depending on the crop selected (e.g., sugarcane images are sent to the sugarcane disease prediction backend).

### Checklist 
- [x] I have tested the changes locally
- [x] Changes are backward-compatible

### Screenshots (if applicable)

https://github.com/user-attachments/assets/a526b4a6-151a-4f65-89a8-cee7719fc529

- Instead of previous AI Engine Button, these Cards will redirect users to the specific models of the crop. This will help in scaling the disease prediction models where we can add more models easily.

Screenshot 2024-10-10 at 1 14 24 AM

- These texts are dynamic and are different for each crops for better explanations!

Screenshot 2024-10-10 at 1 14 37 AM

### Additional Notes
- **Upcoming Enhancements**:
  - The next issue will focus on creating the results page for sugarcane disease predictions.
  - The result pages for other crops will also be revamped to follow the new design structure.

---

Let me know if you need further adjustments!

### CODE REVIEW

**Comment by IkkiOcean** [comment]
I gonna focus on the result page on the next issue since it will need some backend changes too, for example the description and information coming from backend aren't enough and does not provide much information to the user.
I plan to make more detailed result page.

**Comment by manikumarreddyu** [comment]
15 varieties should be there ..check it once ..as now you did for 9 varieties...check in main website you will get it

**Comment by manikumarreddyu** [comment]
Everything looks fine...add remaining also

**Comment by IkkiOcean** [comment]
> 15 varieties should be there ..check it once ..as now you did for 9 varieties...check in main website you will get it

yeah I will add all of them with the next one

**Comment by IkkiOcean** [comment]
@manikumarreddyu  pull request #228 is going to conflict with my work since I'm also working on the UI of same page

Screenshot 2024-10-10 at 1 14 24 AM

what should we do about it?

**Comment by manikumarreddyu** [comment]
There will be no conflicts..since I have reverted the previous PR

**Comment by manikumarreddyu** [comment]
I'm not going to merge that #228 ..so no worries

**Comment by IkkiOcean** [comment]
> There will be no conflicts..since I have reverted the previous PR

what should I do about the cards, my cards are different and act as buttons to redirect to the upload page.

**Comment by IkkiOcean** [comment]
> I'm not going to merge that #228 ..so no worries

okay

**Comment by manikumarreddyu** [comment]
Come to linkedin once...

**Pull request merged**
