### PR TITLE
Addition of B2T | Issue #184

### PR DESCRIPTION
**Pull request by Shariq2003**
# Pull Request

### Title
Addition of B2T

### Description
Addition of B2T

### Related Issues
#184 

### Checklist 

- [X] I have tested the changes locally
- [X] Documentation has been updated (if necessary)
- [X] Changes are backward-compatible

https://github.com/user-attachments/assets/bf4822c6-4814-4c4e-882b-07a4103f79ec

### CODE REVIEW

**Comment by Shariq2003** [comment]
See the deiffrences

**Comment by Shariq2003** [comment]
> Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/manikumarreddyu/AgroTech-AI/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

You can also see them in the deployment preview

**Comment by manikumarreddyu** [comment]
https://agro-tech-ai.vercel.app/

check here..

**Comment by manikumarreddyu** [comment]
both are same...i said before you started working itself...

**Comment by Shariq2003** [comment]
> https://agro-tech-ai.vercel.app/
> 
> check here..

This is the preview deploy.

**Comment by Shariq2003** [comment]
https://github.com/user-attachments/assets/5345eda3-abb9-4cd5-a47a-8f467fd66f11

This is the new deployment

**Comment by Shariq2003** [comment]
image
Check this one

**Comment by Shariq2003** [comment]
https://agro-tech-efbtoex60-manikumarreddyus-projects.vercel.app/

**Comment by manikumarreddyu** [comment]
https://agro-tech-ai.vercel.app/

record for this also

**Comment by Shariq2003** [comment]
> https://agro-tech-ai.vercel.app/
> 
> check here..

This is the main branch branch deployment sir,
How the changes will reflect there without the merging of this PR

**Comment by Shariq2003** [comment]
> https://agro-tech-ai.vercel.app/
> 
> record for this also

Sir this is the main branch deployment.

**Comment by manikumarreddyu** [comment]
join fast...i dont have more time..

**Pull request closed without merging**
