### PR TITLE
Update Climate.jsx

### LINKED ISSUE #304: [Feature Request]: Redesigning Advanced Weather API with Automatic Location Fetching and Detailed Forecasting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

.

### Use Case

.

### Benefits

.

### Add ScreenShots

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
# Pull Request

### Title
Redesigning Advanced Weather API with Automatic Location Fetching and Detailed Forecasting 

### Description
Redesigning Advanced Weather API with Automatic Location Fetching and Detailed Forecasting 

### Related Issues
Resolves #304

### Changes Made
Redesigning Advanced Weather API with Automatic Location Fetching and Detailed Forecasting 

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### CODE REVIEW

**Comment by Hemu21** [comment]
@manikumarreddyu  no level label is needed for this @MastanSayyad

**Comment by MastanSayyad** [comment]
@manikumarreddyu I already told you to add labels to actual worked PRs instead of dummy PRs, even if you add then add lower labels + with proper details and description, A reviewer once reviewers the code then he can only see on line of code with no meaning!

**Comment by MastanSayyad** [comment]
image

See the guidelines I saw you repo and you're favouring few people and making them to top on the leaderboard which is affecting other contributors scores

**Comment by J-B-Mugundh** [comment]
@Hemu21 @MastanSayyad Let me share what I did in backend and which didnt get reflected here. The code was in breaking state and was in live. I ran the same in my local, understood the issue and had a couple of gmeets with the PA and helped him solve it. I should've raised the PR for that. But, I was stupid that I didn't and left it to the PA. 

image
image
image
image

Till this time, I was there with the PA upto nearly 2.30 pm. I can't prove the same as I didn't text him after the gmeet was over and I was tired like anything and slept.

**Pull request merged**
