### PR TITLE
updated forecast api

### PR DESCRIPTION
**Pull request by mishradev1**
# Pull Request

### Title
Updated Forecast API which was not working properly
### Description
The main error here was the placement of .env file which was not in the root directory and was causing trouble as I kept changing api's but the call was not being made.
Also the input format was not correctly followed previously as it wanted inputs as latitude and longitude not as places, for which i introduced another api to handle it.
### Related Issues
None
### Changes Made
Bug Fix
### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
issue-resolved

### Additional Notes
Please upgrade the tag for GSSoC to level-2 if possible as it took a hell lot of debugging :)

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
image


it is showing error like this...

**Comment by mishradev1** [comment]
sorry for the inconvenience, i will look into it and get back to you in a bit.

**Comment by mishradev1** [comment]
The error here is that I updated the .env file with the new key but while pushing the code, it got into .gitignore and was not pushed

**Comment by mishradev1** [comment]
Do consider the request on the additional note above if possible.

**Comment by manikumarreddyu** [comment]
"aec9b7d9badbe062b1cfed513fd5903d"
 
 remove quotes aec9b7d9badbe062b1cfed513fd5903d give it directly and check it once before pushing

**Comment by manikumarreddyu** [comment]
can you please send me the video of working of forecast...are you running on your local before pushing..?

**Comment by mishradev1** [comment]
The code is working just fine on my part and I have cross checked it locally twice.
I think the issue is arising because of the file structure of the document as .env should be in the root folder and not in src 
Please look into the file structure once

**Comment by mishradev1** [comment]
Yeah sure I will send you the video in a minute

**Comment by manikumarreddyu** [comment]
> The code is working just fine on my part and I have cross checked it locally twice. I think the issue is arising because of the file structure of the document as .env should be in the root folder and not in src Please look into the file structure once

can we have google meet once 

https://meet.google.com/gcn-upit-srp

join if you are free and share your screen once..i will check it once and we will fix the erros

**Pull request closed without merging**
