### PR TITLE
chatbot integrated

### PR DESCRIPTION
**Pull request by SunkaraboinaPraveenKumar**
# Pull Request
Issue No: #151 

### Title

ChatBot Integration
### Description

Integrated ChatBot using Groq API for lightening fast response and llama-3.1-8b-instant model for this.

### Related Issues

Issue No: #151 

### Changes Made

ChatBot Integrated with neat UI.

### Screenshots (if applicable)

Screenshot (167)
Screenshot (166)

### Additional Notes

First Run the AGriBot_Server which is written in python. I have also provided API_key.

Footer
Thank You for assigning please do accept my PR and help me to complete my HacktoberFest.

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hi @SunkaraboinaPraveenKumar please use tailwind css only in jsx file..please dont use css file...
and also use # before issue number..write like this fixes: #151 ..

can you able to train that bot ..with information related to agro tech ai

**Comment by SunkaraboinaPraveenKumar** [comment]
Actually it can give any kind of info related to agriculture and regarding that issue number and css i will do it and send you again a new PR

**Comment by manikumarreddyu** [comment]
change the name to AgroTech-AI_Bot..api name..

**Comment by manikumarreddyu** [comment]
and also if possible..make it aligned with green colours..beacuse it is looking odd..

**Review by SunkaraboinaPraveenKumar — COMMENTED** [review]
Css in jsx done

**Comment by SunkaraboinaPraveenKumar** [comment]
Why am i not able to raise new PR it is showing old one itself to review

**Comment by manikumarreddyu** [comment]
no problem..do it here itself

**Comment by SunkaraboinaPraveenKumar** [comment]
ok I will work on API name and green colors

**Comment by manikumarreddyu** [comment]
image
can we get interface like this..

image


can we get like this in the bottom right corner ..above goto top button
image

**Comment by manikumarreddyu** [comment]
https://www.linkedin.com/in/manikumarreddyu

connect me here..

**Comment by SunkaraboinaPraveenKumar** [comment]
I have already asked for your connection when i try to message showing premium member not able to message

**Comment by manikumarreddyu** [comment]
give me your linkedin link.. i will connect

**Comment by SunkaraboinaPraveenKumar** [comment]
image
Updated

**Comment by SunkaraboinaPraveenKumar** [comment]
https://www.linkedin.com/in/sunkaraboina-praveen-84594a256/

**Comment by SunkaraboinaPraveenKumar** [comment]
You are asking to show message icon in home and enable a alert box there itself for chatbot or what i didnot get clarity

**Comment by manikumarreddyu** [comment]
accet the request in linkedin

**Pull request merged**
