### PR TITLE
sugarcane_disease_pred

### PR DESCRIPTION
**Pull request by IkkiOcean**
# Pull Request

### Title
Ensemble Model for Sugarcane Disease Prediction

### Description
This pull request implements an ensemble model combining MobileNet, InceptionV3, VGG16, Conv2D, and ResNet152 for predicting sugarcane diseases. The model achieves an accuracy of 90.94%, significantly improving upon the individual models.

### Related Issues
Closes : #109 

### Changes Made
- Added a Jupyter notebook implementing an ensemble model for sugarcane disease prediction.
- Combined multiple deep learning architectures: MobileNet, InceptionV3, VGG16, Conv2D, and ResNet152 into a cohesive model.
- Implemented data preprocessing steps, including image augmentation and normalization.
- Conducted model training and evaluation, achieving an overall accuracy of 90.94%.
- Included detailed comments and explanations throughout the notebook for clarity and reproducibility.
- Visualized model performance metrics and comparison graphs for individual models.

### Checklist 
- [x] I have tested the changes locally
- [x] Documentation has been updated
- [x] Changes are backward-compatible

### Model Evaluation

| Model      | Accuracy 
|------------|----------
| MobileNet  | 83.20%   
| VGG16      | 79.76%   
| Conv2D     | 86.06%   
| ResNet152  | 81.21%   
| InceptionV3| 86.06%   
| **Ensemble**  | **90.94%** 

### Additional Notes
This model provides a robust solution for timely diagnosis of sugarcane diseases, which is crucial for improving agricultural productivity.

### CODE REVIEW

**Comment by IkkiOcean** [comment]
Please make it level 3 for GSSOC-ext as I have implemented 5-6 deep learning models and used the best of the them to create an ensemble model which can be implemented easily in the application.

Program : GSSOC-ext and hacktoberfest

**Comment by manikumarreddyu** [comment]
hi @IkkiOcean can you please inlude .h5 or tflite or .pkl file of the model..it will be easy for us to develop frontend and api..

**Comment by manikumarreddyu** [comment]
hi @IkkiOcean do it in new PR..

**Comment by IkkiOcean** [comment]
> hi @IkkiOcean can you please inlude .h5 or tflite or .pkl file of the model..it will be easy for us to develop frontend and api..

- The problem is the model's size totals up to almost 800mb. But the max file size limit which can be uploaded on git can not be more than 100mb. I did gave the link to download the model from my Kaggle notebook at ./models/readme.md
- There is another way to do it which is using git-lfs(large file system) to upload larger files but my quota of git-lfs has been extinguished. I can share the file and you can upload it to the repo using git-lfs.

**Comment by manikumarreddyu** [comment]
Okay 👍

**Comment by manikumarreddyu** [comment]
Upload it to Google drive and share me the link...I will place it in readme file..

**Comment by IkkiOcean** [comment]
> Upload it to Google drive and share me the link...I will place it in readme file..

- [Download Here](https://wetransfer.com/downloads/4d6253b0258b4135697b5b03a2dd213c20241007161855/cc7ee9?t_exp=1728922735&t_lsid=f3bb273e-b07d-4c16-8ff4-14c41371712a&t_rid=Z29vZ2xlLW9hdXRoMnwxMTQzNDYyOTEzOTI3MDk3MzA3MjA=&t_s=download_link&t_ts=1728317935)

I have uploaded the model.zip file at the above url with 6 models required to run the ensemble model. The link will expire after 7 days so be sure to download it and proceed with the files.

**Pull request merged**
