### PR TITLE
Integrated mushroom edibility api, , model and data with other apis

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
# Pull Request

### Title
Integrated mushroom edibility api, model and data with other apis

### Description
Integrated mushroom edibility api, model and data with other apis

### Related Issues
#561

### Changes Made
Integrated mushroom edibility api, model and data with other apis

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### CODE REVIEW

**Comment by Hemu21** [comment]
@manikumarreddyu  level 2 is needed not level3 @MastanSayyad

**Comment by J-B-Mugundh** [comment]
> @manikumarreddyu level 2 is needed not level3 @MastanSayyad

May I please know why just level 2 for this @Hemu21 Just asking, so that I could better understand the open source contributions. Please don't mistake me as arguing.

**Comment by manikumarreddyu** [comment]
hi @J-B-Mugundh he is..just copy pasting the same comment without seeing anything..
please @MastanSayyad ..check this once

**Comment by MastanSayyad** [comment]
@manikumarreddyu He is the Program Manager and Tech lead of gssoc extd, and he is not copy pasting the same comment, this is what I told him to do as we are reviewing all PRs of the contributors

**Comment by manikumarreddyu** [comment]
@MastanSayyad okay..then

**Comment by Hemu21** [comment]
> hi @J-B-Mugundh he is..just copy pasting the same comment without seeing anything.. please @MastanSayyad ..check this once

image

gitignore is always changes according to the features and it is the contributor or developer basic reposibility while pushing the code not to add anything. 

image

This file removed comments.  route is added as it is necessary for the api. it is also contributor or developer basic reposibility while  working with backend and api. if new route is created via funtion.

image

This file is map.

image

datasets

image

actual code and logic implementation.

image

if it is a node project package.json is required. as it is python so requrements.txt is required. it is also contributor or developer basic reposibility while  working with project need to mention what packages he/she used.



@J-B-Mugundh  we are reviewing all top 100 contributors prs. the moto of open-source and gssoc is to make everyone learn and we giving benefits to top contributors for their contributions as it should help in adding their resume as open source contributor. If adding the ml projects the data sets won't count towards the code ,level, points. I hope you understand. 


@manikumarreddyu  I hope you understand. Why i said level2. I not just copying. I am reviewing everything. We not only removing the particular contributor or only for your repo. We checking all and removing everything.  If that's the can you please explain me why you given level 3 to this pr https://github.com/manikumarreddyu/AgroTech-AI/pull/310  as it doesn'y have anything just removal to comment.

**Comment by manikumarreddyu** [comment]
hi @Hemu21 then whaat about ipynb file and models..are they created by god...what about building accurate model with less bundle size...

please try to coontribute for my project with one new idea along with best dataset and best api along with optimized pkl or.h5 files..then you will definitely face the pain ...

**Comment by manikumarreddyu** [comment]
when it comes to PR #310.. you contact once with @MastanSayyad ..we had discussed about that for half day ig...ask him once

**Comment by Hemu21** [comment]
> hi @Hemu21 then whaat about ipynb file and models..are they created by god...what about building accurate model with less bundle size...
> 
> please try to coontribute for my project with one new idea along with best dataset and best api along with optimized pkl or.h5 files..then you will definitely face the pain ...

It not the case about pa concern toward the contributor. You seeing the your contributors. we had few ml repos also and we made the ml repos, docs update repos some points limit. you are giving all level3 for the prs. It doesn't effect you but it will effect the contributors. I hope you understand.

**Comment by Hemu21** [comment]
> when it comes to PR #310.. you contact once with @MastanSayyad ..we had discussed about that for half day ig...ask him once

I asked about How you can give level3 for the comment removal pr. As pa you have to review the pr before adding labels.  but you given level 3. I asked Mastan about it. he said he discussed with you long ago but you doesn't removed the label and today when we again pointed you removed the lable.

**Comment by manikumarreddyu** [comment]
> > when it comes to PR #310.. you contact once with @MastanSayyad ..we had discussed about that for half day ig...ask him once
> 
> I asked about How you can give level3 for the comment removal pr. As pa you have to review the pr before adding labels. but you given level 3. I asked Mastan about it. he said he discussed with you long ago but you doesn't removed the label and today when we again pointed you removed the label.

lol

**Comment by manikumarreddyu** [comment]
hi @Hemu21 you are having some ego problems i think..when i am speaking about this PR ..why you are deviating to other PRs...

**Comment by J-B-Mugundh** [comment]
> > hi @Hemu21 then whaat about ipynb file and models..are they created by god...what about building accurate model with less bundle size...
> > please try to coontribute for my project with one new idea along with best dataset and best api along with optimized pkl or.h5 files..then you will definitely face the pain ...
> 
> It not the case about pa concern toward the contributor. You seeing the your contributors. we had few ml repos also and we made the ml repos, docs update repos some points limit. you are giving all level3 for the prs. It doesn't effect you but it will effect the contributors. I hope you understand.

Hi @Hemu21 I understand you. But the thing is, I'm not randomly copying the implementation code from online and running and turning it to model. As you would know, the model size of CNN's would be from 250mb to GBs. I take time to cut out the layers, quantize the same and then merge and upload it. I also take so much of time explaining the things how they're working and raise the issue only when things are fine. I believe it's not very easy to upload a file greater than 100mb to a github repo and even if we could, everytime when a user is going to use it, it'll take a long time. 

PFA for the convo I had for creating a new CNN model and pruning the layers while maintaining the model's accuracy as well. If this is not being considered as enough work. Then it's fine. I'll go with you. 

image
image

**Comment by manikumarreddyu** [comment]
hi @Hemu21 this project is not a like ML-REPOS....please keep in mind..we had so much respect and we are working 24/7 without having proper sleep since 4 months...

@Hemu21 if you are a true open source contributor.....and you have any guts o contribute to this project.. i will really appreciate you....

even if i dont have support from GSSOC i can able to complete my project....
i am here to fight for the valuable work done by the contributors of GSSOC ...

**Comment by manikumarreddyu** [comment]
hi @Hemu21 i have never seen such a narrow minded guy like you....have you read the above ones..are you blind or what..

you are not feeling the pain behind a PR

**Comment by manikumarreddyu** [comment]
GUNTUR vs ONGOLE...

lets see who will win about this #562 PR label issue

**Comment by MastanSayyad** [comment]
@manikumarreddyu This is not how we talk on a public platform to the officials who are just doing their work,,, when someone asks for explanation then you should do that, he is doing his work and I request not to comment or pass judgement when you dont know about the person, he is one of the most heardwroking manager of gssoc and rank 3 contributor for gssoc 24  he simply ask for reduction of points which we are doing in each repo with all contributors, if you have explained everything like this is the changes this is why we did it these are the outcomes etc then we can understand right?

image

image

The argument would have done politely but you are just passing comments without knowing the the person 

The problem is such high labels for each PR of the contributor + that too with empty PR description, you should know that it is necessary to add proper details if you are adding high levels 

It is understandable that you ae giving levels but when we discussed few weeks back I told you again and again to add proper description to your PRs, you also agreed to that, I was reffering to these situations.

in guidelines its given that 

image

All his PRs has level 3 so it is natural to ask questions why did we added the  labels 
image

@sanjay-kv we need your assistence here. this could have done politely.

**Comment by J-B-Mugundh** [comment]
@Hemu21 @MastanSayyad @manikumarreddyu Guys, please! Let's calm down!

**Comment by MastanSayyad** [comment]
> GUNTUR vs ONGOLE...
> 
> lets see who will win about this #562 PR label issue

This is not a fight brother, we said we are reviwing the contributors not the project, he simply asked for expliantion, this is not regional fight, if you have explain him clearly we could have moved on but why you pass comments, this is reallt disappointing

**Comment by J-B-Mugundh** [comment]
Guys! Please! We don't have to take it this far. Please calm down everyone.

**Comment by manikumarreddyu** [comment]
> > GUNTUR vs ONGOLE...
> > lets see who will win about this #562 PR label issue
> 
> This is not a fight brother, we said we are reviwing the contributors not the project, he simply asked for expliantion, this is not regional fight, if you have explain him clearly we could have moved on but why you pass comments, this is reallt disappointing

not like that @MastanSayyad he is from guntur... beside our native place only..these people are so hardworking..no problem with that...you are saying he is top 3 in gssoc right ??..as an open source developer..one can contribute 365 days a year not only during gssoc or hactoberfest event...ask him to take the project to anothet level....

**Comment by J-B-Mugundh** [comment]
@Hemu21 @MastanSayyad https://github.com/manikumarreddyu/AgroTech-AI/pull/562#issuecomment-2438355590 - I explained my side here. Please review rest of the PRs and let me know if I'm going on a wrong side. It's my first time in open source, didn't know much. And I'm grateful that you guys could pin point how to contribute and everyday I'm learning new things. Thank you!

**Comment by manikumarreddyu** [comment]
hey @MastanSayyad @sanjay-kv i m very sorry for being little harsh...please forgive me..

**Comment by manikumarreddyu** [comment]
https://github.com/daccotta-org/daccotta/pull/154

for 9 extra lines level 2...

here for creating a whoke new mini project ..

1.collecting dataset
2.writing our own map file
3.writing ipynb file
4.creating bundles
5 .creating api

still level 2 ??

**Comment by aditya-bhaumik** [comment]
@manikumarreddyu dont worry we are reviewing all the pull requests

**Comment by MastanSayyad** [comment]
> [daccotta-org/daccotta#154](https://github.com/daccotta-org/daccotta/pull/154)
> 
> for 9 extra lines level 2...
> 
> here for creating a whoke new mini project ..
> 
> 1.collecting dataset 2.writing our own map file 3.writing ipynb file 4.creating bundles 5 .creating api
> 
> still level 2 ??

@manikumarreddyu As said we are reviewing all contributors I have reviewed his 80+ PRs and there are 143+ total PRs. due to this discussion I stopped the reviewing. defending your contributors is okay but degrading other contributors us not, review is still under process.

image

I removed his multiple level 3s to level 1 and level 2, we are doing this with all contributors

image

we mentioned that we are asking question because the PR didn't had any explanation or description it is good tat you guys contact on LinkedIn but why linkedin when your own discord PA channel in gssoc server and in github you have PR comment section, github discussion, that's very noble of you that you are defending contributors but when someone officially asks you something then it is your responsibility to answer politely. 

after looking and seeing the snaps given by @J-B-Mugundh I can see Models and being created, that is what we were asking from the start, because there are repos where contributors add readymde ML projects and different models, for which we can only given level 1 or level 2 that's why when reviewed you repo we found the similar pattern and we simply asked for explanation. but you are justifying pain which is only known by you yes indeed there is pain brother but how will we know? 


so do we have pain, I'm reviewing the contributors since 4:30 AM morning, handling multiple contributors there queries and other stuffs at the same time. Your repo and this contributor is not the only case. 

we are reviewing everyone!

**Comment by J-B-Mugundh** [comment]
> > [daccotta-org/daccotta#154](https://github.com/daccotta-org/daccotta/pull/154)
> > for 9 extra lines level 2...
> > here for creating a whoke new mini project ..
> > 1.collecting dataset 2.writing our own map file 3.writing ipynb file 4.creating bundles 5 .creating api
> > still level 2 ??
> 
> @manikumarreddyu As said we are reviewing all contributors I have reviewed his 80+ PRs and there are 143+ total PRs. due to this discussion I stopped the reviewing. defending your contributors is okay but degrading other contributors us not, review is still under process.
> 
> image
> 
> I removed his multiple level 3s to level 1 and level 2, we are doing this with all contributors
> 
> image
> 
> we mentioned that we are asking question because the PR didn't had any explanation or description it is good tat you guys contact on LinkedIn but why linkedin when your own discord PA channel in gssoc server and in github you have PR comment section, github discussion, that's very noble of you that you are defending contributors but when someone officially asks you something then it is your responsibility to answer politely.
> 
> after looking and seeing the snaps given by @J-B-Mugundh I can see Models and being created, that is what we were asking from the start, because there are repos where contributors add readymde ML projects and different models, for which we can only given level 1 or level 2 that's why when reviewed you repo we found the similar pattern and we simply asked for explanation. but you are justifying pain which is only known by you yes indeed there is pain brother but how will we know?
> 
> so do we have pain, I'm reviewing the contributors since 4:30 AM morning, handling multiple contributors there queries and other stuffs at the same time. Your repo and this contributor is not the only case.
> 
> we are reviewing everyone!

Thanks @MastanSayyad! From now, I'll ensure that whatever being done is explained and necessary details happening in behind the scenes are also being added suitably! Please rest assured. Thanks so much for your efforts. Really appreciate that.

**Pull request merged**
