### PR TITLE
feat : Added Hover Effect to the Testimonial Part

### PR DESCRIPTION
**Pull request by abishek1740P**
# Pull Request

### Title

Enhancement: Hover Effects on Testimonial Slider

### Description

This PR introduces hover effects to the Testimonial Slider component. The key updates include:

Button Hover Effect:

The Next and Previous buttons now scale up with a smooth transition (hover:scale-125), providing a more interactive and engaging user experience.
Testimonial Card Hover Effect:

Each testimonial card scales up slightly when hovered (hover:scale-110), creating a visually appealing highlight effect for individual testimonials. This enhances the overall user interaction with the slider.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Additional Notes

Consider this under hacktoberfest2024 , hacktoberfest-accepted, GSSOC-ext.

Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hi @abishek1740P mention Issue number in description.... like #1 like that..which ever is your issue number

**Comment by manikumarreddyu** [comment]
please provide issue number in description..so that when we close the PR then issue also automatically closes..otherwise it is very hard to find where the issue to close it...i think you understand my point...

**Comment by abishek1740P** [comment]
@manikumarreddyu  issue #54

**Comment by manikumarreddyu** [comment]
@abishek1740P please mention it in the pull request description

**Comment by manikumarreddyu** [comment]
any how i am merging it..from next time onwards make sure to mention in pr description

**Pull request merged**
